import json
import random
import time
import uuid
import os

# Configuration
OUTPUT_FILE = 'capture_data.json'
SAMPLES_PER_CLASS = 10
CLASSES = ['A', 'B', 'C', 'D', 'E']
FRAMES_PER_SAMPLE = 5  # Keeping it small for dummy data

def generate_random_landmark():
    return {
        "x": random.random(),
        "y": random.random(),
        "z": random.random()
    }

def generate_sample(label):
    sample_id = str(uuid.uuid4())
    now = int(time.time() * 1000)
    
    frames = []
    for i in range(FRAMES_PER_SAMPLE):
        # Generate 21 landmarks
        landmarks = [generate_random_landmark() for _ in range(21)]
        
        frame = {
            "t": i * 33, # ~30fps
            "score": 0.9 + random.random() * 0.1,
            "landmarks": landmarks,
            "features": {
                "norm": landmarks, # In real app these are normalized, but for dummy data raw is fine
                "angles": {}, # Optional
                "fingerState": {} # Optional
            }
        }
        frames.append(frame)

    return {
        "id": sample_id,
        "label": label,
        "type": "static",
        "handedness": "Right",
        "frames": frames,
        "summary": {
            "durationMs": FRAMES_PER_SAMPLE * 33
        },
        "timestamp": now
    }

def main():
    print(f"Generating dummy data for classes: {CLASSES}")
    samples = []
    
    for label in CLASSES:
        for _ in range(SAMPLES_PER_CLASS):
            samples.append(generate_sample(label))
            
    dataset = {
        "meta": {
            "dataset": "dummy-validation-set",
            "version": "1.0",
            "createdAt": "2026-01-14T00:00:00.000Z",
            "fps": 30,
            "notes": "Generated by generate_dummy_data.py"
        },
        "samples": samples
    }
    
    # Save to root (where app expects it or where training script expects it?)
    # train_static.py expects '../capture_data.json' relative to its location in ml_pipeline/
    # effectively matching the project root.
    
    output_path = OUTPUT_FILE
    # If running from root, it goes to capture_data.json
    
    with open(output_path, 'w') as f:
        json.dump(dataset, f, indent=2)
        
    print(f"Successfully generated {len(samples)} samples to {output_path}")

if __name__ == "__main__":
    main()
